# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import api2msl_pb2 as proto_dot_api2msl__pb2


class Api2MslStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJson = channel.unary_unary(
                '/api2visual.Api2Msl/GetJson',
                request_serializer=proto_dot_api2msl__pb2.BundleRequest.SerializeToString,
                response_deserializer=proto_dot_api2msl__pb2.JsonReply.FromString,
                )


class Api2MslServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJson(self, request, context):
        """Interface for sending encoded video frame and get predicted Json path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Api2MslServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJson,
                    request_deserializer=proto_dot_api2msl__pb2.BundleRequest.FromString,
                    response_serializer=proto_dot_api2msl__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api2visual.Api2Msl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Api2Msl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api2visual.Api2Msl/GetJson',
            proto_dot_api2msl__pb2.BundleRequest.SerializeToString,
            proto_dot_api2msl__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
